// Auto-generated Supabase configuration
// Do not edit this file manually

export const projectId = import.meta.env.VITE_SUPABASE_PROJECT_ID || '';
export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || '';
export const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || '';
