/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "mtualrcxwessdsxocwgd"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10dWFscmN4d2Vzc2RzeG9jd2dkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAwODY5NTgsImV4cCI6MjA5NTY2Mjk1OH0.-AxL5uGZyM0Yy-k7o3ZvuTy9XSmyA0UNmeibrQGyAd8"